{% set name = "y-py" %}
{% set version = "0.5.9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/y/y_py/y_py-{{ version }}.tar.gz
  sha256: 50cfa0532bcee27edb8c64743b49570e28bb76a00cd384ead1d84b6f052d9368

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=0.14,<0.15                   # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - maturin >=0.14,<0.15
    - pip
    - python
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - y_py

about:
  home: https://github.com/y-crdt/ypy
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Python bindings for the Rust port of Yjs
  dev_url: https://github.com/y-crdt/ypy

extra:
  recipe-maintainers:
    - davidbrochart
    - Waidhoferj
    - fcollonval
